### ISSUE TITLE
Getting started link results in a 403

### ISSUE THREAD

**Issue by NinovanderMark** [microsoft/GDK#1]
The README contains a link to help getting started with a development environment. It contains the following link

https://review.docs.microsoft.com/en-us/gaming/gdk/_content/gc/getstarted/dev-pc-setup?branch=main

However this link requires one to login. When I login with my personal Microsoft account I'm met with a 403 Forbidden error.

What are the requirements for accessing this link? Isn't the GDK supposed to be free for anyone to learn now?

Hoping to hear back soon.

**Comment by mseminatore** [comment]
+1 this does appear to be an incorrect link.

**Comment by pauliver** [comment]
This link should be docs.microsoft.com not review.docs.microsoft.com 

https://docs.microsoft.com/en-us/gaming/gdk/_content/gc/getstarted/dev-pc-setup
