### ISSUE TITLE
[System] GameInput on PC isn’t yet available. 

### ISSUE THREAD

**Issue by FLY1NGSQU1RR3L** [microsoft/GDK#11]
The following APIs aren’t yet implemented in GameInput. They'll be available in a future update. 
 - IGameInput::GetTemporalReading 
 - IGameInput::RegisterReadingCallback 
 - IGameInput::CreateAggregateDevice 
 - IGameInputDevice::GetBatteryState 
 - IGameInputDevice::PowerOff

**Comment by FLY1NGSQU1RR3L** [comment]
Current plan of record:  June 2022 GDK will begin to release part or all of the interfaces required to support GameInput on PC w/ the GDK.

**Comment by Devaniti** [comment]
@DJm00n whole GameInput is not available in public GDK yet.

**Comment by DJm00n** [comment]
Looks like GameInput is now included in recent `Microsoft.GDK.PC.220600 10.0.22000.4362` package:

`native\220600\GRDK\gamekit\Include\GameInput.h`
`native\220600\GRDK\gamekit\lib\amd64\GameInput.lib`

Corresponding redist comes with Windows 10 build 18362 (the “Windows 10 May 2019 Update”).

More info here: https://github.com/microsoft/GDK/releases/tag/June_2022

**Comment by r2d2Proton** [comment]
I did run into a few of them myself. The raw stuff too - GetRawDeviceFeature, etc. More importantly though my USB Xbox controllers are not working. They do work in XInput and I would have expected the same in the latest GameInput API. Keyboard and mouse do work, USB Xbox 360 controller - no. That is bad code. Bade Code Review. Bad testing. Can you point me to a sample in the Windows-Driver-Sample that I can start from to create my own version of the interface?

**Comment by spencerparkin** [comment]
What's the licensing for GameInput?  Can anyone write an application using it?  Or do we have to wait until it's part of the windows SDK?

**Comment by DJm00n** [comment]
@spencerparkin https://github.com/microsoft/GDK/blob/Main/LICENSE-EN-US.MD

**Comment by spencerparkin** [comment]
@DJm00n SIGH..................I'll have my lawyer read all that and make sense of it for me.  Thanks.

**Comment by LordOfDragons** [comment]
Taking a quick look at the licensing there it seems this is not usable by an open source game engine. Can you please clarify if an open source project in general can legally safely use the public GDK as available on NuGet?

Furthermore I tried using the public GDK from NuGet (the one supposed to contain GameInput.h) but it is broken. I find GameInput.h in the packages directory but VisualStudio refuses to find the file when using "<include>GameInput.h</include>". Can you fix the NuGet package to properly adjust additional include path as other packages do (like the WinRT ones)?

**Comment by walbourn** [comment]
The first package was a preview, so you should find the 2024 releases are functional.

**Comment by walbourn** [comment]
https://www.nuget.org/packages/Microsoft.GameInput

**Comment by magrega** [comment]
is there a status update on IGameInputDevice::PowerOff?
