### ISSUE TITLE
[Developer Tools] Visual Studio 2019 Lifecycle update

### ISSUE THREAD

**Issue by FLY1NGSQU1RR3L** [microsoft/GDK#18]
**Issue**
Visual Studio 2019 version 16.4 is out of support as of October 2021. 

**Workaround**
Please move to Visual Studio 2019 version 16.7, 16.9, or 16.11 for continued servicing and support. A future GDK release will generate a build error with Visual Studio 2019 version 16.0–16.6—the GDK currently generates a build error if versions 16.0–16.3 are in use.

**Note:** The GDK continues to support using Visual Studio 2017 version 15.9.

For more information, see [Visual Studio Product Lifecycle and Servicing | Microsoft Docs.](https://docs.microsoft.com/en-us/visualstudio/releases/2019/servicing)

**Comment by walbourn** [comment]
Visual Studio 2017 support was removed in October 2023

v141 toolset support for VS 2019/VS 2022 is being removed in October 2024.
