### ISSUE TITLE
PGDK.exe not updated with October update, failed to install

### ISSUE THREAD

**Issue by KuDeSnikDL** [microsoft/GDK#19]
Running PGDK.exe with the latest commit fail to install the October update. It looks like it was not updated with packages - it is left from June version

**Comment by FLY1NGSQU1RR3L** [comment]
Bad commit from a broken branch update. Fixing now, ETA EOD (11/18).

**Comment by FLY1NGSQU1RR3L** [comment]
@KuDeSnikDL  - This appears to have been resolved, but not as cleanly as I would like.  Commit histories were harmed in the propping of this fix, will be making other corrections to my broken scripts.

1. The \Main branch will be kept as the latest and greatest at any time, as the easiest way for people casually browsing or just starting with the GDK to have the latest version.
2. There will be proper \<month> branches to let developers pick and choose the release(s) they want from the archives and commit history.

**Please let me know if you are still having issues.**

![image](https://user-images.githubusercontent.com/14060191/142528124-bf62b2eb-4060-43b9-9471-35a5aa68c226.png)
