### ISSUE TITLE
40+ years of Windows game development?

### ISSUE THREAD

**Issue by photex** [microsoft/GDK#2]
Howdy!

I'm 41 years old. I'm roughly 3 years older than the announcement of Windows. And 5 years older than the first release.

I think the README is off by a decade maybe? :D

**Comment by FLY1NGSQU1RR3L** [comment]
@photex  - great call out.  This was a line combined from an old GDC presentation where I was actually referring to *Microsoft* history (going back to DOS where Bill Gates put his name on Gorilla.BAS).  Will fix, thank you :)
