### ISSUE TITLE
PC Samples also closed?

### ISSUE THREAD

**Issue by BMarques** [microsoft/GDK#3]
Are the PC Samples really meant to be closed? https://docs.microsoft.com/en-us/gaming/gdk/_content/gc/get-started-with-pc-dev/running-samples/running-samples-pc

Without the samples, I'm finding it hard to be interested on learning how to use the GDK.

**Comment by BMarques** [comment]
Not interested any longer.

**Comment by Devaniti** [comment]
I'm still interested in same issue.
Can you please reopen it?

**Comment by FLY1NGSQU1RR3L** [comment]
All PC-side samples are going to be open in a new repository soon.  Will link to this repo as soon as our documentation updates and repo updates are complete.

**Comment by FLY1NGSQU1RR3L** [comment]
PC-side samples that can be built using the GDK and some Xbox samples that require the GDKX (GDK w/ Xbox Extensions) are now available.

https://github.com/Microsoft/Xbox-ATG-Samples#:~:text=Xbox-ATG-Samples%201%20Kits%20contains%20support%20code%20used%20by,desktop%20PC%20platform%20Graphics%20IntroGraphics%20More%20items...%20

**Comment by BMarques** [comment]
Thanks Clint.

I was looking at the link, you mean this: https://github.com/microsoft/Xbox-GDK-Samples/ ?
