### ISSUE TITLE
[Documentation] GameInputKind enum documentation is not consistent with header file

### ISSUE THREAD

**Issue by ShadowMarker789** [microsoft/GDK#31]
[GameInputKind](https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/reference/input/gameinput/enums/gameinputkind) documentation is not consistent with the header file 

![screenshot-comparison](https://user-images.githubusercontent.com/37165910/191657425-3ef0fa49-254e-4a97-af29-6f2cae015ad8.png)

I was hoping to issue a PR to correct it, but there's no option to?

![page-screenshot](https://user-images.githubusercontent.com/37165910/191657645-100ef2ec-d2d8-4dc8-ac0a-a1876c9a8e54.png)

The `GameInput.h` relevant enum is this:

```cpp
typedef enum GameInputKind
{
    GameInputKindUnknown          = 0x00000000,
    GameInputKindRawDeviceReport  = 0x00000001,
    GameInputKindControllerAxis   = 0x00000002,
    GameInputKindControllerButton = 0x00000004,
    GameInputKindControllerSwitch = 0x00000008,
    GameInputKindController       = 0x0000000E,
    GameInputKindKeyboard         = 0x00000010,
    GameInputKindMouse            = 0x00000020,
    GameInputKindTouch            = 0x00000100,
    GameInputKindMotion           = 0x00001000,
    GameInputKindArcadeStick      = 0x00010000,
    GameInputKindFlightStick      = 0x00020000,
    GameInputKindGamepad          = 0x00040000,
    GameInputKindRacingWheel      = 0x00080000,
    GameInputKindUiNavigation     = 0x01000000,
    GameInputKindAny              = 0x0FFFFFFF
} GameInputKind;
```

Can someone with appropriate auth and access double-check the docs against the header file and correct as needed?

Thanks

**Comment by ShadowMarker789** [comment]
I'd like to revise this issue with the latest changes made 2023-03-16 

![image](https://user-images.githubusercontent.com/37165910/231342041-d62e0e90-bf12-4254-84be-c9122d28378d.png)

It is now unfortunately missing the entry for `GameInputKindAny` which holds value `0x0FFFFFFF`

**Comment by MaKiPL** [comment]
+1
I'm using 230600 GDK and it's still missing this one. I had to #define the missing 0x0FFFFFFF and static_cast to GameInputKind when used with several methods

**Comment by bbowman** [comment]
@MaKiPL the `GameInputKindAny` was removed as it was causing more issues for games in practice. Usually a game is looking for a specific kind or kind(s) of inputs and should be explicit about this. Sorry for the confusion here as it should have been marked in the 2210 GDK release notes as a breaking change but it looks like that was missed.
