### ISSUE TITLE
GameInput Not Working With USB XBox Controller

### ISSUE THREAD

**Issue by r2d2Proton** [microsoft/GDK#32]
Does GameInput support the USB Xbox(360) controller? The controllers work fine with XInput, which I am going try and use sxs in code. Also, XGameRuntimeInitialize returns (0x87e5001f), which apparently is not considered failed FAILED(hr). By chance, can you point me to a sample in the Windows-Driver-Samples so that I can use as a baseline to create my own for the controllers?

![XGameRuntimeInitializeFails](https://user-images.githubusercontent.com/4054178/208248754-3ac1bda1-d2c0-4e12-9dab-8e433fa1672c.png)

**Comment by DJm00n** [comment]
>By chance, can you point me to a sample in the Windows-Driver-Samples so that I can use as a baseline to create my own for the controllers?

There is no any public official way to add your own XInput compatible controller. But you can create a generic HID gamepad (see [vhidmini2](https://github.com/microsoft/Windows-driver-samples/tree/main/hid/vhidmini2) example etc). 

Reverse engineered driver exist that can emulate XInput compatible controller programmatically: https://github.com/nefarius/ViGEmBus
For example, famous [DS4Windows](https://github.com/Ryochan7/DS4Windows) tool is using it under the hood to emulate XInput controller
