### ISSUE TITLE
[Suggestion] Add xWMAEncode.exe tool from GDKX to GDK.

### ISSUE THREAD

**Issue by Marlax0** [microsoft/GDK#33]
It doesn't seem like the tool should be GDKX exclusive.
XAudio2 supports both ADPCM and xWMA for Windows, and ADPCMEncode.exe is already included with GDK.
PC games use the format all the time. Even games from Microsoft have used the format on PC.
Also, xWMAEncode.exe was previously (and is currently) available freely anyway, via the old DirectX SDK.

XAudio2 with xWMA support is used in several example projects across Microsoft's repositories.
It's confusing that the ability to encode it can only be done freely through an unsupported legacy SDK.
(This was my experience.)

Perhaps something should be done about this?

**Comment by walbourn** [comment]
Thanks.

This was fixed for the October 2023 release.
