### ISSUE TITLE
missing E_GAME_MISSING_GAME_CONFIG define in XGameErr.h

### ISSUE THREAD

**Issue by apache-hb** [microsoft/GDK#43]
The error code [documentation](https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/reference/errorcodes) suggests this error code is defined in XGameErr.h, It appears to be missing.

**Comment by walbourn** [comment]
That error code doesn't appear to exist. You should file a doc bug on that page.

**Comment by walbourn** [comment]
I was incorrect. It defined just not included in that header.

**Comment by walbourn** [comment]
I filed a bug with the team on this issue.
