### ISSUE TITLE
Can't find XInputOnGameInput.h

### ISSUE THREAD

**Issue by mitridas** [microsoft/GDK#47]
Hi, I'm working on a PC game.
Just done a clean installation of the GDK but XInputOnGameInput.h is nowhere to be found. I'd expect it to be next to GameInput.h?

[According to the official doc](https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/reference/input/xinputongameinput/xinputongameinput_members) it should be there, or am I missing something?

**Comment by walbourn** [comment]
This header only ships in the *Microsoft GDK with Xbox Extensions*. It's just a compat layer so you can potentially use older XInput input code on Xbox via an adapter for GameInput.

For PC, you would just use XInput directly.

See https://walbourn.github.io/xinput-and-windows-8/
