### ISSUE TITLE
Installation script not signed

### ISSUE THREAD

**Issue by jgedri** [microsoft/GDK#5]
The installation script {Installers/InstallGamingServicesBundle.ps1) isn't signed.

**Comment by FLY1NGSQU1RR3L** [comment]
Thank you for reporting this.  Reviewing with the team and will advise shortly.

**Comment by FLY1NGSQU1RR3L** [comment]
8/6 Update: we investigated multiple files that are not being signed due to how they were being packaged and distributed before the GDK going public.  These are being rectified for the next June 2021 GDK Update expected this month or next.

**Comment by jgedri** [comment]
Thank you for looking into the matter.

**Comment by FLY1NGSQU1RR3L** [comment]
Will be fixed in the next June 2021 GDK Update 2.
