### ISSUE TITLE
cannot use it

### ISSUE THREAD

**Issue by vvp3** [microsoft/GDK#58]
hi,

1. i cannot use gdk becasue i have 64 bit 
2. i want to use gdxk but i cannot download anything even if I paid the 14 usd requested for creator program ... do I need to do soemthing else ?

**Comment by djspringate** [comment]
1. Sorry can you provide more information here? The GDK is 64-bit? What’s the problem you’re having?
2. GDKX isn’t available open source but only to secure developer partners. More information is available at the following link: https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/getstarted/overviews/access-resources

**Comment by vvp3** [comment]
Hi.

32bit is not working for me and I need the xdk to begin work in Unity and test achievements in sandbox ...

Azure team entered with me in all my setting and everything is ok.
I paid the 19 usd fee for creator program.
No matter what I do and with what user I connect (full permisssions and also entra id correctly set up) I cannot access any 
 link in resources.
I paid to get access to develop and I cannot ... I get no real answers from customer support. The only ones who were great were azure ones.
I get no email from someone in the xbox team nor I find any email where I can adress the issues I have.

Can somones message me in rpivate at least an email adress to speak with someone in Microsoft Developer partners team ?

**Comment by walbourn** [comment]
For Unity on PC, please take those issues to https://github.com/microsoft/gdk-unity-package

For Unity on Xbox, please use private developer forums
