### ISSUE TITLE
GitHub Actions integration

### ISSUE THREAD

**Issue by flibitijibibo** [microsoft/GDK#59]
SDL currently has a PR that adds a CI test for Windows GDK...

https://github.com/libsdl-org/SDL/pull/8847

... but it's currently being blocked by the build time, which is currently 25 minutes! 23 of those 25 minutes are the installer:

https://github.com/libsdl-org/SDL/actions/runs/7536289619/job/20513496746?pr=8847

The workflow currently uses the install scripts in this repo. Is there a way to strip down the install process to what's needed to compile and link GDK binaries and nothing else? Some of the *BSDs currently in CI take ~10 minutes, so even cutting the time in half would probably be enough to merge this in.

**Comment by walbourn** [comment]
Have you looked at using a NuGet package instead?

https://www.nuget.org/packages?q=MIcrosoft.GDK.PC
