### ISSUE TITLE
GameOS file does not exist - Error code: 0x80070002

### ISSUE THREAD

**Issue by MarceloGh05t** [microsoft/GDK#69]
We follow the gdk packaging steps for xbox from this link: https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/packaging/overviews/packaging-getting-started-for-console

However, the following error appeared in the last step of "Package creation: Run makepkg pack /lk SECRET_KEY.lekb /f layout.xml /d <Your_Game_Folder_Name> /pd <Output_Folder_Name>":

No GameOS file specified with /gameos switch. Defaulting to C:\BREAKING BRICKS\gameos.xvd
Games file 'C:\BREAKING BRICKS\gameos.xvd' does not exist.

Package creation failed and validation step was skipped, to get more details, try running "makepkg validate".
GameOS file does not exist - Error code: 0x80070002

At no point in the tutorial does it teach you how to create the xvd file. How can we resolve the error?

**Comment by WilliamsJason** [comment]
Are you intending to package for console or the Microsoft Store in Windows? For PC you should use this page: https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/packaging/overviews/packaging-getting-started-for-pc

For console, make sure you have the version of the GDK with the Xbox Extensions (GDKX), which is available to licensed partners in a managed program (https://aka.ms/gdkdl). That installation contains the associated gameos.xvd file.
