### ISSUE TITLE
Status of GameInput on Windows

### ISSUE THREAD

**Issue by akbyrd** [microsoft/GDK#78]
I attempted to use GameInput on Windows and realized that it's not in a functional state. Half of the API is not implemented, 360 controllers do not work, HID information is not available, absolute mouse position is not available, etc. It looks like the API has been available on Windows since June of 2021 and presumably these issues have existed throughout that time.

Over the last few months there have been a few NuGet releases and categories applied to GitHub issues, but it doesn't appear that any progress has been made on reported issues.

My question is: "what is the current state of GameInput on Windows"? Is it being supported? Is there active work to finish implementing it? Should I attempt to use it in new projects? Is there an approximate timeline on when it will be in a production ready state?

My current understanding is that GameInput is not suitable for use in any project and will not be within the next few years. But I'd love to be wrong because there's a lot to like about the API.

**Comment by walbourn** [comment]
A few things to note:

* GameInput on Windows is supported. It is in fact "in box" with the recent releases of the Windows OS.

* Absolute mouse position was never a goal of the API. The GameInput mouse support is designed to replace the "RawInput" model of mouse control. For absolute position, you just use classic Win32 messages as always.

* The GitHub Issues is a 'best effort' area for feedback. I agree that the area has gone a bit stale.
