### ISSUE TITLE
GameInput.lib for arm64

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/GDK#80]
It looks like Arm64 installs of Windows contain GameInput.dll and GameInputSvc.exe. Can the nuget package be updated to include the arm64 version of GameInput.lib so Arm64 apps can be built against GameInput?

**Comment by walbourn** [comment]
The lib for arm64 is not yet available. When it is, it will be in [Microsoft.GameInput](https://www.nuget.org/packages/Microsoft.GameInput/).

**Comment by ThadHouse** [comment]
Any update to this? Its been almost a year, and multiple 1.x releases, but no arm builds.

**Comment by ThadHouse** [comment]
@walbourn I notice that https://www.nuget.org/packages/Microsoft.GameInput/2.0.26100.5334 still doesn't include this. Can we get this issue reopened so someone actually remembers to do this? Missing arm64 is a big miss, especially since the DLL is included in the OS. So this should be trivial.

**Comment by AshleyScirra** [comment]
I tried an ARM64 build of a Win32 app using GameInput which failed with an unresolved external and then found this issue, so I'm hoping for this too!

**Comment by Alovchin91** [comment]
~~Looks like it's available in the latest v3.3 update now: https://www.nuget.org/packages/Microsoft.GameInput/3.3.163~~

_EDIT:_
Nope, even though the release notes mention "native support for ARM", the nuget package seems to still lack the ARM64 .lib. @walbourn Is it a mistake in the release notes or in the packaging?

**Comment by walbourn** [comment]
I'm following up with the GameInput team.

**Comment by walbourn** [comment]
The missing ARM64 version of the lib is an oversight. The release note is because the GameInputRedist.MSI now includes the ARM64 version of the DLL and service. They will spin a new build of the NuGet soon to add the missing link lib, but you could build from source using `GameInput.cpp` for ARM64 and it should work now.
