### ISSUE TITLE
VS 2022 support?

### ISSUE THREAD

**Issue by directhex** [microsoft/GDK#9]
Right now, building stuff w/ VS2022 installed throws an error complaining `error MSB8020: The build tools for v143 (Platform Toolset = 'v143') cannot be found`

**Comment by FLY1NGSQU1RR3L** [comment]
@directhex 

**This is a known issue.**  You will need to update to the October 2021 GDK release **and** use the .VSIX installers that will be uploaded shortly.

> **Workaround Publishing Soon** | GDK Visual Studio 2022 Preview Support.  </br> The upcoming release of Visual Studio 2022 will provide several benefits to game developers, including a more scalable 64-bit IDE and an improved debugger architecture, among other key features. The October 2021 version of the GDK includes a preview of Visual Studio 2022 support. Support for Visual Studio 2022 in the October 2021 GDK is provided by a set of .vsix files that can manually be installed into Visual Studio.  The .VSIX installer scripts will be uploaded to the public repo (ETA week of November 15th).</br>

**Comment by FLY1NGSQU1RR3L** [comment]
**@directhex** quick update, the team is putting VS2022 install support package together later this week.  Thanks for your patience as we align our GDK and VS installer scripts; this is just a temporary solution.

**Comment by akoeplinger** [comment]
@FLY1NGSQU1RR3L do you have an update on when VS2022 support will be ready?

**Comment by FLY1NGSQU1RR3L** [comment]
@akoeplinger  - apologies, fixing our release branch structure to help developers manage which release they want to stabilize on.  That update will come with the new ..VSIX installers to support VS2022; ETA 24-48hrs while I rebuild our scripts to keep the releases more separate.

Just a preview:  The GDK has three major feature releases every year (Spring, Summer, Fall) and a variable schedule of updates w/ fixes to each.  This has been confusing to developers who have not been living inside the Xbox ecosystem when this model was established.  So while I always recommend you grab "latest and greatest," the reality is game teams in the middle of development want to have as little disruption as possible.  We'll make sure that's clear on our repos and the VS2022 support update is just waiting on me to clean up the releases here first.

**Comment by steveisok** [comment]
@FLY1NGSQU1RR3L Do you have any update? Has anything changed re: VS2022 support?

**Comment by FLY1NGSQU1RR3L** [comment]
Fixed! https://github.com/microsoft/GDK/issues/17
